export const CHAT_INPUT_TOKEN_BUDGET = 12000;
export const CHAT_OUTPUT_TOKEN_BUDGET = 4000;
export const EXTENDED_CHAT_INPUT_TOKEN_BUDGET = 45000;
export const EXTENDED_USER_CONTEXT_TOKEN_BUDGET = 20000;
export const CORPUS_CONTEXT_ALLOCATION = 4096;
